### ISSUE TITLE
console message doesn't inform the process status of Mysql-related Model

### ISSUE THREAD

**Issue by projectxmaker** [paulomcnally/grunt-loopback-auto#1]
Hi,

I have a Model configured with Mysql datasource as below, the module does create related table properly but it doesn't inform any console message like what it does for Mongo-related Model. Furthermore, it seems we need a done() command to finalize the module's process when it's finished.

``` html
  "MyModel": {
    "dataSource": "mysql",
    "public": false
  },
```

**Comment by paulomcnally** [comment]
Fixed: https://github.com/paulomcnally/grunt-loopback-auto/commit/4f0870299349f13aab662a4df16c69f61addb758

Pelase upgrade to 0.0.4 and test. [https://www.npmjs.org/package/grunt-loopback-auto](https://www.npmjs.org/package/grunt-loopback-auto)

**Comment by bluestaralone** [comment]
my MyQL-related Model cannot be generated, and i see the message below:

``` html
MyModel ignored -> DataSource: mysql
```

**Comment by paulomcnally** [comment]
@bluestaralone you need set dataSource: 'mysql'. See: https://github.com/paulomcnally/grunt-loopback-auto/blob/master/Gruntfile.js#L22

**Comment by projectxmaker** [comment]
@paulomcnally: I think the issue @bluestaralone facing here is when his loopback is configured to work with both Mysql and Mongodb, then there will have some Mysql-related Models and some Mogodb-related Models. So the issue could not be solved by reconfiguring datasource info.

**Comment by paulomcnally** [comment]
I need an example to understand what the problem

**Comment by bluestaralone** [comment]
@paulomcnally: It's ok now. thanks.

**Comment by projectxmaker** [comment]
@paulomcnally 

the issue is solved if we set further options in Gruntfile like this

``` html
      'db_autoupdate': {
        options: {
          dataSource: 'mongodb',
          app: './server/server',
          config: './server/model-config',
          method: 'autoupdate'
        },
        options: {
          dataSource: 'mysql',
          app: './server/server',
          config: './server/model-config',
          method: 'autoupdate'
        }
      }
```

thanks
